#%RAML 0.8
title: 1b-case
version: 1.0
/phonenumber:
  get: 
    queryParameters: 
      phone:
        example: 00000
        required: true
        type: string
    responses: 
      200: 
        body: 
          application/json: 
            example: |
              [
                {
                  "Phone":"12345",
                  "Account_Number":"122222222",
                  "Balance":"100000.00",
                  "Provider":"HDFC Bank"
                },
                {
                  "Phone":"678910",
                  "Account_Number":"45645645",
                  "Balance":"7851654.00",
                  "Provider":"SBI Bank"
                }
              ]